[package]
name = "znai-rust-showcase"
version = "0.1.0"
edition = "2021"
description = "Calculates changes in Elo ratings"
license-file = "LICENSE"

[dependencies]
clap = {version = "4.4.4", features = ["derive"]}
